# Generated by Django 5.0.6 on 2024-05-22 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('lead', models.TextField()),
                ('corpo', models.TextField()),
                ('fechamento', models.TextField(blank=True, null=True)),
                ('autor', models.CharField(max_length=100)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_alteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('miniatura', 'Miniatura'), ('post', 'Post'), ('banner', 'Banner'), ('default', 'Default')], max_length=20)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
        ),
    ]
