# Generated by Django 5.0.6 on 2024-05-25 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_add_status_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news'),
        ),
    ]
