# Generated by Django 5.0.6 on 2024-05-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_corpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='corpo',
            field=models.TextField(),
        ),
    ]
