# Generated by Django 5.0.6 on 2024-05-26 03:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_corpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='corpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
